// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRyH7W9q059PHUuO7qzNKgHgbZRlz7HRQ',
    appId: '1:906080772758:web:3f1a23b17c2957582a98b7',
    messagingSenderId: '906080772758',
    projectId: 'mcproject-535d5',
    authDomain: 'mcproject-535d5.firebaseapp.com',
    storageBucket: 'mcproject-535d5.firebasestorage.app',
    measurementId: 'G-2HBVFR2YM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIF1zwhtHKSrjFHrD0qFZXFu3S7aioGFM',
    appId: '1:906080772758:android:f2cad1d63fe3e2392a98b7',
    messagingSenderId: '906080772758',
    projectId: 'mcproject-535d5',
    storageBucket: 'mcproject-535d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRAYMmhoFHSQ6EukfY_T0D-WTXIX1LAog',
    appId: '1:906080772758:ios:13e4a229997210ac2a98b7',
    messagingSenderId: '906080772758',
    projectId: 'mcproject-535d5',
    storageBucket: 'mcproject-535d5.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRAYMmhoFHSQ6EukfY_T0D-WTXIX1LAog',
    appId: '1:906080772758:ios:13e4a229997210ac2a98b7',
    messagingSenderId: '906080772758',
    projectId: 'mcproject-535d5',
    storageBucket: 'mcproject-535d5.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRyH7W9q059PHUuO7qzNKgHgbZRlz7HRQ',
    appId: '1:906080772758:web:20e78e1daccae8212a98b7',
    messagingSenderId: '906080772758',
    projectId: 'mcproject-535d5',
    authDomain: 'mcproject-535d5.firebaseapp.com',
    storageBucket: 'mcproject-535d5.firebasestorage.app',
    measurementId: 'G-KNJ8SBGC52',
  );
}
